FROM caddy:alpine


# ------ COPY NGINX CONFIG ------
COPY caddy/open/config/Caddyfile /etc/caddy/Caddyfile
COPY site-content /srv

# ------ COPY KEYS ------
RUN mkdir /keys
COPY shared/cert/keys /keys