FROM nginx:1.27.2

# ------ COPY NGINX CONFIG ------

RUN rm -rf /usr/share/nginx/html/*
COPY site-content /data/www

RUN rm -f /etc/nginx/nginx.conf
COPY nginx/domains_defaultB/config/*.conf /etc/nginx/

# ------ COPY KEYS ------
RUN mkdir /keys
COPY shared/cert/keys /keys