FROM litespeedtech/litespeed:6.3.1-lsphp81


# ------ COPY CONFIG ------
RUN rm -rf /usr/local/lsws/conf/templates
RUN rm -rf /usr/local/lsws/conf/cert

COPY closedlitespeed/domains_certA_defaultB_strict_default/config/conf /usr/local/lsws/conf

# ------ COPY KEYS AND CONTENT ------
COPY shared/cert/keys /keys
COPY site-content /srv