FROM nginx:stable-alpine


# ------ COPY NGINX CONFIG ------

RUN rm -rf /usr/share/nginx/html/*
COPY ./site-content /data/www

RUN rm -f /etc/nginx/nginx.conf
COPY .1nginx/paths/config/nginx.conf /etc/nginx/nginx.conf

COPY .1nginx/paths/config/conf.d /etc/nginx/conf.d

# ------ COPY KEYS ------

RUN mkdir /keys
COPY ./cert/keys /keys