FROM nginx:1.27.2

# ------ COPY NGINX CONFIG ------

RUN rm -rf /usr/share/nginx/html/*
COPY _site-content /data/www

RUN rm -f /etc/nginx/nginx.conf
COPY nginx/{{ folderName }}/config/*.conf /etc/nginx/

# ------ COPY KEYS ------
RUN mkdir /keys
COPY _shared/cert/keys /keys
