FROM caddy:2.8.4-alpine


# ------ COPY CADDY CONFIG ------
COPY caddy/{{ folderName }}/Caddyfile /etc/caddy/Caddyfile
COPY site-content /srv

# ------ COPY KEYS ------
RUN mkdir /keys
COPY shared/cert/keys /keys