FROM caddy:2.8.4

# ------ COPY CADDY CONFIG ------
COPY caddy/{{ folderName }}/config/Caddyfile /etc/caddy/Caddyfile
COPY _site-content /srv

# ------ COPY KEYS ------
RUN mkdir /keys
COPY _shared/cert/keys /keys
