FROM caddy:2.8.4-alpine


# ------ COPY NGINX CONFIG ------
COPY caddy/paths/config/Caddyfile /etc/caddy/Caddyfile
COPY site-content /srv

# ------ COPY KEYS ------
RUN mkdir /keys
COPY shared/cert/keys /keys